// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace EvaluacionCredito.Tests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class PagoElectronicoPinPadFeature : object, global::Xunit.IClassFixture<PagoElectronicoPinPadFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("es"), "Features", "Pago electrónico (PinPad)", "  Como cajero del sistema de cobros\r\n  Quiero procesar pagos con tarjeta en el Pi" +
                "nPad\r\n  Para registrar pagos aprobados y manejar rechazos correctamente", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "PagoElectronico.feature"
#line hidden
        
        public PagoElectronicoPinPadFeature(PagoElectronicoPinPadFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 8
  #line hidden
#line 9
    await testRunner.GivenAsync("que estoy autenticado en el sistema de caja", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 10
    await testRunner.AndAsync("tengo una venta lista para cobrar en el PinPad", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/PagoElectronico.feature.ndjson", 6);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="CU5 - Pago aprobado")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Pago electrónico (PinPad)")]
        [global::Xunit.TraitAttribute("Description", "CU5 - Pago aprobado")]
        [global::Xunit.InlineDataAttribute("Tarjeta Credito", "0", new string[0])]
        [global::Xunit.InlineDataAttribute("Tarjeta Debito", "1", new string[0])]
        public async global::System.Threading.Tasks.Task CU5_PagoAprobado(string tarjeta, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Tarjeta", tarjeta);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("CU5 - Pago aprobado", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 12
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
  await this.FeatureBackgroundAsync();
#line hidden
#line 13
    await testRunner.WhenAsync(string.Format("intento cobrar con la {0}", tarjeta), ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 14
    await testRunner.AndAsync("el emisor autoriza la transacción", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 15
    await testRunner.ThenAsync("el pago debe registrarse como \"aprobado\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
#line 16
    await testRunner.AndAsync("se debe emitir el comprobante con la tarjeta utilizada", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="CU5 - Pago no aprobado")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Pago electrónico (PinPad)")]
        [global::Xunit.TraitAttribute("Description", "CU5 - Pago no aprobado")]
        [global::Xunit.InlineDataAttribute("Tarjeta Credito", "2", new string[0])]
        [global::Xunit.InlineDataAttribute("Tarjeta Debito", "3", new string[0])]
        public async global::System.Threading.Tasks.Task CU5_PagoNoAprobado(string tarjeta, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Tarjeta", tarjeta);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("CU5 - Pago no aprobado", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 23
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
  await this.FeatureBackgroundAsync();
#line hidden
#line 24
    await testRunner.WhenAsync(string.Format("intento cobrar con la {0}", tarjeta), ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 25
    await testRunner.AndAsync("el emisor rechaza la transacción", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 26
    await testRunner.ThenAsync("el pago debe registrarse como \"no aprobado\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
#line 27
    await testRunner.AndAsync("no se debe emitir comprobante", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await PagoElectronicoPinPadFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await PagoElectronicoPinPadFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
